-- ============================================
-- Replace Prompts with New Fun, Light Pool
-- ============================================

-- Clear existing prompts
DELETE FROM prompts;

-- Insert new TEXT prompts (100 total)
INSERT INTO prompts (text, prompt_type) VALUES
  -- Reflective but light (1-40)
  ('What''s a small moment from your past that still makes you smile?', 'text'),
  ('Tell us about a time something didn''t go as planned but turned out fine.', 'text'),
  ('What''s something you used to be really into?', 'text'),
  ('Tell us about a time you laughed at yourself.', 'text'),
  ('What''s a random skill you have?', 'text'),
  ('What''s something you''ve gotten better at over time?', 'text'),
  ('Tell us about a time you tried something new.', 'text'),
  ('What''s a small habit that makes your day better?', 'text'),
  ('What''s something you once thought was overrated but now enjoy?', 'text'),
  ('Tell us about a time you were pleasantly surprised.', 'text'),
  ('What''s a memory that always makes you laugh?', 'text'),
  ('What''s something you enjoy doing more than most people?', 'text'),
  ('Tell us about a time you felt proud of something small.', 'text'),
  ('What''s a place you''ve been that you''d happily return to?', 'text'),
  ('What''s something you''re oddly good at?', 'text'),
  ('Tell us about a time you went slightly outside your comfort zone.', 'text'),
  ('What''s something you used to dislike but grew to like?', 'text'),
  ('What''s a decision you''re glad you made?', 'text'),
  ('Tell us about a time you tried and failed, but it wasn''t a big deal.', 'text'),
  ('What''s something you''ve changed your mind about?', 'text'),
  ('What''s a funny misunderstanding you''ve been part of?', 'text'),
  ('What''s something that always improves your mood?', 'text'),
  ('Tell us about a time you underestimated something (or someone).', 'text'),
  ('What''s a small win you had recently?', 'text'),
  ('What''s something you''ve learned just by experience?', 'text'),
  ('What''s a simple pleasure you really enjoy?', 'text'),
  ('Tell us about a time you did something spontaneous.', 'text'),
  ('What''s something you enjoy doing when you have free time?', 'text'),
  ('What''s a memory that feels very "you"?', 'text'),
  ('What''s something you''re currently enjoying?', 'text'),
  ('What''s a moment that made you think "that was fun"?', 'text'),
  ('What''s something you''re glad you tried at least once?', 'text'),
  ('Tell us about a time you made the best of a boring situation.', 'text'),
  ('What''s something you''ve gotten into recently?', 'text'),
  ('What''s a small thing that makes your day nicer?', 'text'),
  ('Tell us about a time you surprised yourself (in a good way).', 'text'),
  ('What''s something you enjoy sharing with others?', 'text'),
  ('What''s a random fact about you?', 'text'),
  ('What''s something you look forward to each week?', 'text'),
  ('What''s a moment that still makes you chuckle when you think about it?', 'text'),

  -- Social and people-focused (41-70)
  ('Who''s someone you enjoy spending time with?', 'text'),
  ('What''s something people often associate with you?', 'text'),
  ('Who''s someone you had a big crush on in the past but don''t anymore?', 'text'),
  ('What''s something you appreciate more now than before?', 'text'),
  ('What''s something you''re glad you learned?', 'text'),
  ('Who''s someone who always makes you laugh?', 'text'),
  ('What''s a trait you admire in other people?', 'text'),
  ('What''s something you enjoy doing by yourself?', 'text'),
  ('What''s something you wish you had more time for?', 'text'),
  ('Who''s someone you''d happily hang out with again?', 'text'),
  ('What''s something you enjoy teaching or explaining?', 'text'),
  ('What''s something that helps you unwind?', 'text'),
  ('What''s something you''re curious about lately?', 'text'),
  ('What''s something that helps you feel comfortable?', 'text'),
  ('Who''s someone you feel lucky to know?', 'text'),
  ('What''s something you''ve come to appreciate over time?', 'text'),
  ('What''s something you enjoy more now than you did a few years ago?', 'text'),
  ('What''s something that helps you feel relaxed?', 'text'),
  ('What''s something that feels very familiar to you?', 'text'),
  ('Who''s someone you enjoy catching up with?', 'text'),
  ('What''s something you''ve learned about yourself recently?', 'text'),
  ('What''s something that helps you reset?', 'text'),
  ('What''s something you''re glad exists?', 'text'),
  ('What''s something you enjoy talking about?', 'text'),
  ('What''s something you find comforting?', 'text'),
  ('What''s something that makes you feel at ease?', 'text'),
  ('What''s something you''re excited about right now?', 'text'),
  ('What''s something you''ve grown to enjoy?', 'text'),
  ('What''s something that makes you feel content?', 'text'),
  ('What''s something that feels like a treat to you?', 'text'),

  -- Would you rather + simple pleasures (71-100)
  ('Would you rather always have a plan or always wing it?', 'text'),
  ('Would you rather be early or right on time?', 'text'),
  ('Would you rather explore a new place or revisit a favorite?', 'text'),
  ('Would you rather have more free time or more energy?', 'text'),
  ('Would you rather cook at home or eat out?', 'text'),
  ('Would you rather live near the ocean or in a city?', 'text'),
  ('Would you rather start your day early or late?', 'text'),
  ('Would you rather plan trips or be surprised?', 'text'),
  ('Would you rather text or talk on the phone?', 'text'),
  ('Would you rather have one big adventure a year or lots of small ones?', 'text'),
  ('What''s something you find oddly satisfying?', 'text'),
  ('What''s a routine you enjoy?', 'text'),
  ('What''s something you could do for hours without noticing time pass?', 'text'),
  ('What''s a place that feels comforting to you?', 'text'),
  ('What''s something you enjoy sharing with friends?', 'text'),
  ('What''s something that makes you feel relaxed instantly?', 'text'),
  ('What''s a simple thing you really enjoy?', 'text'),
  ('What''s something that makes you nostalgic (in a good way)?', 'text'),
  ('What''s something you''d happily do again?', 'text'),
  ('What''s something you enjoy learning about?', 'text'),
  ('What''s something that makes you smile without trying?', 'text'),
  ('What''s something you''re glad you said yes to?', 'text'),
  ('What''s something that always makes a day better?', 'text'),
  ('What''s a question you enjoy being asked?', 'text'),
  ('What''s something you appreciate when it''s quiet?', 'text'),
  ('What''s something that makes you feel playful?', 'text'),
  ('What''s something you enjoy doing with other people?', 'text'),
  ('What''s something you''d recommend to a friend?', 'text'),
  ('What''s something that feels like a treat to you?', 'text'),
  ('What''s something that makes you feel good in a simple way?', 'text');

-- Insert PHOTO prompts (5 total)
INSERT INTO prompts (text, prompt_type) VALUES
  ('Take a photo of your surroundings.', 'photo'),
  ('Take a selfie.', 'photo'),
  ('Take a selfie with someone else (can be a pet).', 'photo'),
  ('Take a photo of something random nearby.', 'photo'),
  ('Take a photo that represents your current mood.', 'photo');
